"""empty message

Revision ID: 685dece69a88
Revises: None
Create Date: 2016-09-08 15:56:59.174657

"""

# revision identifiers, used by Alembic.
revision = '685dece69a88'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('pub_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'pub_date')
    ### end Alembic commands ###
